# Site Settings
title:               Hanezu
tagline:             ようこそジプシー、我が神秘のブログに
description:         Hanezu's blog.
baseurl:             
url:                 "https://hanezu.github.io"
github:
  url:               "https://hanezu.github.io/"
author:
  name:              "Hanezu Syun"
  email:             "tim.zhc@gmail.com"
  twitter:           "hanezu_syun"
  instagram:         ""
  github:            "hanezu"
  facebook:          "Huachun Zhu"
  linkedin:          "huachun-zhu-ab5541b2"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
