title:  Hanezu
tagline:  眩しさだけは、忘れなかった。

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'hanezu'

google-ID: 'UA-109662927-1'

menu:
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'ブログ', path: 'menu', url: 'ja.html'}
- {name: '博客', path: 'menu', url: 'cn.html'}
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}
#- {name: 'Archive', path: 'menu', url: 'archive.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/hanezu'}
- {icon: 'twitter', link: 'https://twitter.com/hanezu_haru'}
#- {icon: 'instagram', link: 'https://www.instagram.com/hanezu_shun/'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/huachun/'}
- {icon: 'envelope', link: 'mailto:huachun@crypko.ai'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}


# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
