title:  Hanezu
tagline:  ようこそジプシー、我が神秘のブログに

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'hanezu'

google-ID: 'UA-109662927-1'

menu:
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}
- {name: 'Archive', path: 'menu', url: 'archive.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/hanezu'}
- {icon: 'twitter', link: 'https://twitter.com/hanezu_shun'}
- {icon: 'instagram', link: 'https://www.instagram.com/hanezu_shun/'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/huachun/'}
- {icon: 'envelope', link: 'mailto:tim.zhc@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
